# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74c36454ce649b728080a9eadbf56095bdd2d8f5461ffb13df273147baeeb2a07f45beefabbc2b7e6f65ebd992cc3d4cc7421328f4b15d43d20e9c7e8988c7dd

test:
  secret_key_base: ddca0f1bd720f74d82d7c0fe4e563ad9ed3578c42e3e0c1defdbad6869e8a825387692f4e5283f6ce2f93c9745490459686d21983e8a7a8fea7ff5f4be200ab9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
